# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9791c725b42ed855d42ed2abbfebe4914432e9f88d9e59d9c1294b7e54526264fcdef817bdaee8cf546724edb9f7e6947c73e94ac5018ccef55260f528448c3

test:
  secret_key_base: 3deb0d09dcbb2583713a01eea080f97d7c842557aa71e98c39345e83724229fdd0003e2effcc2e4490cabea34a39280e4ed628eaec8d440233fc84cebac7bf97

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
