json.extract! @user, 
              :display_name, 
              :id, 
              :email, 
              :description, 
              :main, 
              :pronouns, 
              :age, 
              :game,
              :image_url,
              :contact_info
